/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lleclerc_jnilink_SayHelloMain */

#ifndef _Included_com_lleclerc_jnilink_SayHelloMain
#define _Included_com_lleclerc_jnilink_SayHelloMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lleclerc_jnilink_SayHelloMain
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lleclerc_jnilink_SayHelloMain_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
